@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0ODk2MTY1NywianRpIjoiNjIxYTI3OGItOGRiNi00NTA1LWE2MmQtNTg5MzZiNTRlNWZlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjE2NTk0NmFlLTE0MzQtNDY3My1iZWZjLTVhZmRkYTMzODc0NiIsIm5iZiI6MTc0ODk2MTY1NywiY3NyZiI6ImYzOGViNDU3LWVjNGYtNGY0NC1hOTMwLWI4ODY5NzRhNDdjMCIsImV4cCI6MTc0ODk2MjU1N30.v-2Z8i8ks0EC1VSFLkC74x1mzrZQVV2CgcCznFk57Qc
### login
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "testapiuser1",
  "password": "idl1"
}

### get list of component
GET http://localhost:5000/user/components
Authorization: {{token}}




### generate pat
POST http://localhost:5000/generate-pat
Content-Type: application/json
Authorization: {{token}}

{
  "user_id": "be6cccdd-35e8-4742-a24e-dd313493a5c9",
  "application_id": "72b6e92a-97ec-4a5b-9756-227f286a321d",
  "role_id": "2a97d959-e7c9-49a6-bbce-cad598d2468b"
}

### get all pat for user
GET http://localhost:5000/user/pats?user_id=165946ae-1434-4673-befc-5afdda338746
Authorization: {{token}}